// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addGuildConfigStmt, err = db.PrepareContext(ctx, addGuildConfig); err != nil {
		return nil, fmt.Errorf("error preparing query AddGuildConfig: %w", err)
	}
	if q.addGuildRoleReadAccessStmt, err = db.PrepareContext(ctx, addGuildRoleReadAccess); err != nil {
		return nil, fmt.Errorf("error preparing query AddGuildRoleReadAccess: %w", err)
	}
	if q.addGuildRoleWriteAccessStmt, err = db.PrepareContext(ctx, addGuildRoleWriteAccess); err != nil {
		return nil, fmt.Errorf("error preparing query AddGuildRoleWriteAccess: %w", err)
	}
	if q.addGuildUserAccessStmt, err = db.PrepareContext(ctx, addGuildUserAccess); err != nil {
		return nil, fmt.Errorf("error preparing query AddGuildUserAccess: %w", err)
	}
	if q.addGuildUserWriteAccessStmt, err = db.PrepareContext(ctx, addGuildUserWriteAccess); err != nil {
		return nil, fmt.Errorf("error preparing query AddGuildUserWriteAccess: %w", err)
	}
	if q.addMatchStmt, err = db.PrepareContext(ctx, addMatch); err != nil {
		return nil, fmt.Errorf("error preparing query AddMatch: %w", err)
	}
	if q.addMatchModeratorStmt, err = db.PrepareContext(ctx, addMatchModerator); err != nil {
		return nil, fmt.Errorf("error preparing query AddMatchModerator: %w", err)
	}
	if q.addMatchStreamerStmt, err = db.PrepareContext(ctx, addMatchStreamer); err != nil {
		return nil, fmt.Errorf("error preparing query AddMatchStreamer: %w", err)
	}
	if q.addMatchTeamStmt, err = db.PrepareContext(ctx, addMatchTeam); err != nil {
		return nil, fmt.Errorf("error preparing query AddMatchTeam: %w", err)
	}
	if q.addMatchTeamResultsStmt, err = db.PrepareContext(ctx, addMatchTeamResults); err != nil {
		return nil, fmt.Errorf("error preparing query AddMatchTeamResults: %w", err)
	}
	if q.addNotificationStmt, err = db.PrepareContext(ctx, addNotification); err != nil {
		return nil, fmt.Errorf("error preparing query AddNotification: %w", err)
	}
	if q.addParticipationRequirementsStmt, err = db.PrepareContext(ctx, addParticipationRequirements); err != nil {
		return nil, fmt.Errorf("error preparing query AddParticipationRequirements: %w", err)
	}
	if q.closeParticipationEntryStmt, err = db.PrepareContext(ctx, closeParticipationEntry); err != nil {
		return nil, fmt.Errorf("error preparing query CloseParticipationEntry: %w", err)
	}
	if q.countAllMatchesStmt, err = db.PrepareContext(ctx, countAllMatches); err != nil {
		return nil, fmt.Errorf("error preparing query CountAllMatches: %w", err)
	}
	if q.countAllNotificationsStmt, err = db.PrepareContext(ctx, countAllNotifications); err != nil {
		return nil, fmt.Errorf("error preparing query CountAllNotifications: %w", err)
	}
	if q.countDisabledGuildsStmt, err = db.PrepareContext(ctx, countDisabledGuilds); err != nil {
		return nil, fmt.Errorf("error preparing query CountDisabledGuilds: %w", err)
	}
	if q.countEnabledGuildsStmt, err = db.PrepareContext(ctx, countEnabledGuilds); err != nil {
		return nil, fmt.Errorf("error preparing query CountEnabledGuilds: %w", err)
	}
	if q.countMatchesStmt, err = db.PrepareContext(ctx, countMatches); err != nil {
		return nil, fmt.Errorf("error preparing query CountMatches: %w", err)
	}
	if q.countNotificationsStmt, err = db.PrepareContext(ctx, countNotifications); err != nil {
		return nil, fmt.Errorf("error preparing query CountNotifications: %w", err)
	}
	if q.decreaseMatchTeamConfirmedParticipantsStmt, err = db.PrepareContext(ctx, decreaseMatchTeamConfirmedParticipants); err != nil {
		return nil, fmt.Errorf("error preparing query DecreaseMatchTeamConfirmedParticipants: %w", err)
	}
	if q.deleteAllMatchModeratorsStmt, err = db.PrepareContext(ctx, deleteAllMatchModerators); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllMatchModerators: %w", err)
	}
	if q.deleteAllMatchStreamersStmt, err = db.PrepareContext(ctx, deleteAllMatchStreamers); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllMatchStreamers: %w", err)
	}
	if q.deleteAllMatchTeamsStmt, err = db.PrepareContext(ctx, deleteAllMatchTeams); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllMatchTeams: %w", err)
	}
	if q.deleteGuildConfigStmt, err = db.PrepareContext(ctx, deleteGuildConfig); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteGuildConfig: %w", err)
	}
	if q.deleteGuildMatchesStmt, err = db.PrepareContext(ctx, deleteGuildMatches); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteGuildMatches: %w", err)
	}
	if q.deleteMatchStmt, err = db.PrepareContext(ctx, deleteMatch); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMatch: %w", err)
	}
	if q.deleteMatchListStmt, err = db.PrepareContext(ctx, deleteMatchList); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMatchList: %w", err)
	}
	if q.deleteMatchModeratorStmt, err = db.PrepareContext(ctx, deleteMatchModerator); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMatchModerator: %w", err)
	}
	if q.deleteMatchModeratorsStmt, err = db.PrepareContext(ctx, deleteMatchModerators); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMatchModerators: %w", err)
	}
	if q.deleteMatchNotificationsStmt, err = db.PrepareContext(ctx, deleteMatchNotifications); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMatchNotifications: %w", err)
	}
	if q.deleteMatchStreamerStmt, err = db.PrepareContext(ctx, deleteMatchStreamer); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMatchStreamer: %w", err)
	}
	if q.deleteMatchStreamersStmt, err = db.PrepareContext(ctx, deleteMatchStreamers); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMatchStreamers: %w", err)
	}
	if q.deleteMatchTeamStmt, err = db.PrepareContext(ctx, deleteMatchTeam); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMatchTeam: %w", err)
	}
	if q.deleteNotificationStmt, err = db.PrepareContext(ctx, deleteNotification); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteNotification: %w", err)
	}
	if q.deleteParticipationRequirementsStmt, err = db.PrepareContext(ctx, deleteParticipationRequirements); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteParticipationRequirements: %w", err)
	}
	if q.disableGuildStmt, err = db.PrepareContext(ctx, disableGuild); err != nil {
		return nil, fmt.Errorf("error preparing query DisableGuild: %w", err)
	}
	if q.getGuildConfigStmt, err = db.PrepareContext(ctx, getGuildConfig); err != nil {
		return nil, fmt.Errorf("error preparing query GetGuildConfig: %w", err)
	}
	if q.getGuildConfigByCategoryStmt, err = db.PrepareContext(ctx, getGuildConfigByCategory); err != nil {
		return nil, fmt.Errorf("error preparing query GetGuildConfigByCategory: %w", err)
	}
	if q.getGuildRoleAccessStmt, err = db.PrepareContext(ctx, getGuildRoleAccess); err != nil {
		return nil, fmt.Errorf("error preparing query GetGuildRoleAccess: %w", err)
	}
	if q.getGuildUserAccessStmt, err = db.PrepareContext(ctx, getGuildUserAccess); err != nil {
		return nil, fmt.Errorf("error preparing query GetGuildUserAccess: %w", err)
	}
	if q.getMatchStmt, err = db.PrepareContext(ctx, getMatch); err != nil {
		return nil, fmt.Errorf("error preparing query GetMatch: %w", err)
	}
	if q.getMatchTeamStmt, err = db.PrepareContext(ctx, getMatchTeam); err != nil {
		return nil, fmt.Errorf("error preparing query GetMatchTeam: %w", err)
	}
	if q.getMatchTeamByRolesStmt, err = db.PrepareContext(ctx, getMatchTeamByRoles); err != nil {
		return nil, fmt.Errorf("error preparing query GetMatchTeamByRoles: %w", err)
	}
	if q.getNotificationByOffsetStmt, err = db.PrepareContext(ctx, getNotificationByOffset); err != nil {
		return nil, fmt.Errorf("error preparing query GetNotificationByOffset: %w", err)
	}
	if q.getParticipationRequirementsStmt, err = db.PrepareContext(ctx, getParticipationRequirements); err != nil {
		return nil, fmt.Errorf("error preparing query GetParticipationRequirements: %w", err)
	}
	if q.hasRoleAccessStmt, err = db.PrepareContext(ctx, hasRoleAccess); err != nil {
		return nil, fmt.Errorf("error preparing query HasRoleAccess: %w", err)
	}
	if q.hasUserAccessStmt, err = db.PrepareContext(ctx, hasUserAccess); err != nil {
		return nil, fmt.Errorf("error preparing query HasUserAccess: %w", err)
	}
	if q.increaseMatchTeamConfirmedParticipantsStmt, err = db.PrepareContext(ctx, increaseMatchTeamConfirmedParticipants); err != nil {
		return nil, fmt.Errorf("error preparing query IncreaseMatchTeamConfirmedParticipants: %w", err)
	}
	if q.isGuildEnabledStmt, err = db.PrepareContext(ctx, isGuildEnabled); err != nil {
		return nil, fmt.Errorf("error preparing query IsGuildEnabled: %w", err)
	}
	if q.listDueNotificationsStmt, err = db.PrepareContext(ctx, listDueNotifications); err != nil {
		return nil, fmt.Errorf("error preparing query ListDueNotifications: %w", err)
	}
	if q.listGuildMatchesStmt, err = db.PrepareContext(ctx, listGuildMatches); err != nil {
		return nil, fmt.Errorf("error preparing query ListGuildMatches: %w", err)
	}
	if q.listGuildRoleAccessStmt, err = db.PrepareContext(ctx, listGuildRoleAccess); err != nil {
		return nil, fmt.Errorf("error preparing query ListGuildRoleAccess: %w", err)
	}
	if q.listGuildUserAccessStmt, err = db.PrepareContext(ctx, listGuildUserAccess); err != nil {
		return nil, fmt.Errorf("error preparing query ListGuildUserAccess: %w", err)
	}
	if q.listMatchModeratorsStmt, err = db.PrepareContext(ctx, listMatchModerators); err != nil {
		return nil, fmt.Errorf("error preparing query ListMatchModerators: %w", err)
	}
	if q.listMatchStreamersStmt, err = db.PrepareContext(ctx, listMatchStreamers); err != nil {
		return nil, fmt.Errorf("error preparing query ListMatchStreamers: %w", err)
	}
	if q.listMatchTeamsStmt, err = db.PrepareContext(ctx, listMatchTeams); err != nil {
		return nil, fmt.Errorf("error preparing query ListMatchTeams: %w", err)
	}
	if q.listNotificationsStmt, err = db.PrepareContext(ctx, listNotifications); err != nil {
		return nil, fmt.Errorf("error preparing query ListNotifications: %w", err)
	}
	if q.listNowAccessibleChannelsStmt, err = db.PrepareContext(ctx, listNowAccessibleChannels); err != nil {
		return nil, fmt.Errorf("error preparing query ListNowAccessibleChannels: %w", err)
	}
	if q.listNowDeletableChannelsStmt, err = db.PrepareContext(ctx, listNowDeletableChannels); err != nil {
		return nil, fmt.Errorf("error preparing query ListNowDeletableChannels: %w", err)
	}
	if q.listNowDueParticipationRequirementsStmt, err = db.PrepareContext(ctx, listNowDueParticipationRequirements); err != nil {
		return nil, fmt.Errorf("error preparing query ListNowDueParticipationRequirements: %w", err)
	}
	if q.nextMatchCounterStmt, err = db.PrepareContext(ctx, nextMatchCounter); err != nil {
		return nil, fmt.Errorf("error preparing query NextMatchCounter: %w", err)
	}
	if q.removeGuildRoleAccessStmt, err = db.PrepareContext(ctx, removeGuildRoleAccess); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveGuildRoleAccess: %w", err)
	}
	if q.removeGuildUserAccessStmt, err = db.PrepareContext(ctx, removeGuildUserAccess); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveGuildUserAccess: %w", err)
	}
	if q.rescheduleMatchStmt, err = db.PrepareContext(ctx, rescheduleMatch); err != nil {
		return nil, fmt.Errorf("error preparing query RescheduleMatch: %w", err)
	}
	if q.resetEventIDStmt, err = db.PrepareContext(ctx, resetEventID); err != nil {
		return nil, fmt.Errorf("error preparing query ResetEventID: %w", err)
	}
	if q.updateCategoryIdStmt, err = db.PrepareContext(ctx, updateCategoryId); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCategoryId: %w", err)
	}
	if q.updateGuildConfigStmt, err = db.PrepareContext(ctx, updateGuildConfig); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateGuildConfig: %w", err)
	}
	if q.updateMatchChannelAccessibilityStmt, err = db.PrepareContext(ctx, updateMatchChannelAccessibility); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMatchChannelAccessibility: %w", err)
	}
	if q.updateMatchEventIDStmt, err = db.PrepareContext(ctx, updateMatchEventID); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMatchEventID: %w", err)
	}
	if q.updateParticipationRequirementsStmt, err = db.PrepareContext(ctx, updateParticipationRequirements); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateParticipationRequirements: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addGuildConfigStmt != nil {
		if cerr := q.addGuildConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addGuildConfigStmt: %w", cerr)
		}
	}
	if q.addGuildRoleReadAccessStmt != nil {
		if cerr := q.addGuildRoleReadAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addGuildRoleReadAccessStmt: %w", cerr)
		}
	}
	if q.addGuildRoleWriteAccessStmt != nil {
		if cerr := q.addGuildRoleWriteAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addGuildRoleWriteAccessStmt: %w", cerr)
		}
	}
	if q.addGuildUserAccessStmt != nil {
		if cerr := q.addGuildUserAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addGuildUserAccessStmt: %w", cerr)
		}
	}
	if q.addGuildUserWriteAccessStmt != nil {
		if cerr := q.addGuildUserWriteAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addGuildUserWriteAccessStmt: %w", cerr)
		}
	}
	if q.addMatchStmt != nil {
		if cerr := q.addMatchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addMatchStmt: %w", cerr)
		}
	}
	if q.addMatchModeratorStmt != nil {
		if cerr := q.addMatchModeratorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addMatchModeratorStmt: %w", cerr)
		}
	}
	if q.addMatchStreamerStmt != nil {
		if cerr := q.addMatchStreamerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addMatchStreamerStmt: %w", cerr)
		}
	}
	if q.addMatchTeamStmt != nil {
		if cerr := q.addMatchTeamStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addMatchTeamStmt: %w", cerr)
		}
	}
	if q.addMatchTeamResultsStmt != nil {
		if cerr := q.addMatchTeamResultsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addMatchTeamResultsStmt: %w", cerr)
		}
	}
	if q.addNotificationStmt != nil {
		if cerr := q.addNotificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addNotificationStmt: %w", cerr)
		}
	}
	if q.addParticipationRequirementsStmt != nil {
		if cerr := q.addParticipationRequirementsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addParticipationRequirementsStmt: %w", cerr)
		}
	}
	if q.closeParticipationEntryStmt != nil {
		if cerr := q.closeParticipationEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing closeParticipationEntryStmt: %w", cerr)
		}
	}
	if q.countAllMatchesStmt != nil {
		if cerr := q.countAllMatchesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAllMatchesStmt: %w", cerr)
		}
	}
	if q.countAllNotificationsStmt != nil {
		if cerr := q.countAllNotificationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAllNotificationsStmt: %w", cerr)
		}
	}
	if q.countDisabledGuildsStmt != nil {
		if cerr := q.countDisabledGuildsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countDisabledGuildsStmt: %w", cerr)
		}
	}
	if q.countEnabledGuildsStmt != nil {
		if cerr := q.countEnabledGuildsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countEnabledGuildsStmt: %w", cerr)
		}
	}
	if q.countMatchesStmt != nil {
		if cerr := q.countMatchesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countMatchesStmt: %w", cerr)
		}
	}
	if q.countNotificationsStmt != nil {
		if cerr := q.countNotificationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countNotificationsStmt: %w", cerr)
		}
	}
	if q.decreaseMatchTeamConfirmedParticipantsStmt != nil {
		if cerr := q.decreaseMatchTeamConfirmedParticipantsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing decreaseMatchTeamConfirmedParticipantsStmt: %w", cerr)
		}
	}
	if q.deleteAllMatchModeratorsStmt != nil {
		if cerr := q.deleteAllMatchModeratorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllMatchModeratorsStmt: %w", cerr)
		}
	}
	if q.deleteAllMatchStreamersStmt != nil {
		if cerr := q.deleteAllMatchStreamersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllMatchStreamersStmt: %w", cerr)
		}
	}
	if q.deleteAllMatchTeamsStmt != nil {
		if cerr := q.deleteAllMatchTeamsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllMatchTeamsStmt: %w", cerr)
		}
	}
	if q.deleteGuildConfigStmt != nil {
		if cerr := q.deleteGuildConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteGuildConfigStmt: %w", cerr)
		}
	}
	if q.deleteGuildMatchesStmt != nil {
		if cerr := q.deleteGuildMatchesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteGuildMatchesStmt: %w", cerr)
		}
	}
	if q.deleteMatchStmt != nil {
		if cerr := q.deleteMatchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMatchStmt: %w", cerr)
		}
	}
	if q.deleteMatchListStmt != nil {
		if cerr := q.deleteMatchListStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMatchListStmt: %w", cerr)
		}
	}
	if q.deleteMatchModeratorStmt != nil {
		if cerr := q.deleteMatchModeratorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMatchModeratorStmt: %w", cerr)
		}
	}
	if q.deleteMatchModeratorsStmt != nil {
		if cerr := q.deleteMatchModeratorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMatchModeratorsStmt: %w", cerr)
		}
	}
	if q.deleteMatchNotificationsStmt != nil {
		if cerr := q.deleteMatchNotificationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMatchNotificationsStmt: %w", cerr)
		}
	}
	if q.deleteMatchStreamerStmt != nil {
		if cerr := q.deleteMatchStreamerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMatchStreamerStmt: %w", cerr)
		}
	}
	if q.deleteMatchStreamersStmt != nil {
		if cerr := q.deleteMatchStreamersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMatchStreamersStmt: %w", cerr)
		}
	}
	if q.deleteMatchTeamStmt != nil {
		if cerr := q.deleteMatchTeamStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMatchTeamStmt: %w", cerr)
		}
	}
	if q.deleteNotificationStmt != nil {
		if cerr := q.deleteNotificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteNotificationStmt: %w", cerr)
		}
	}
	if q.deleteParticipationRequirementsStmt != nil {
		if cerr := q.deleteParticipationRequirementsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteParticipationRequirementsStmt: %w", cerr)
		}
	}
	if q.disableGuildStmt != nil {
		if cerr := q.disableGuildStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing disableGuildStmt: %w", cerr)
		}
	}
	if q.getGuildConfigStmt != nil {
		if cerr := q.getGuildConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGuildConfigStmt: %w", cerr)
		}
	}
	if q.getGuildConfigByCategoryStmt != nil {
		if cerr := q.getGuildConfigByCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGuildConfigByCategoryStmt: %w", cerr)
		}
	}
	if q.getGuildRoleAccessStmt != nil {
		if cerr := q.getGuildRoleAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGuildRoleAccessStmt: %w", cerr)
		}
	}
	if q.getGuildUserAccessStmt != nil {
		if cerr := q.getGuildUserAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGuildUserAccessStmt: %w", cerr)
		}
	}
	if q.getMatchStmt != nil {
		if cerr := q.getMatchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMatchStmt: %w", cerr)
		}
	}
	if q.getMatchTeamStmt != nil {
		if cerr := q.getMatchTeamStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMatchTeamStmt: %w", cerr)
		}
	}
	if q.getMatchTeamByRolesStmt != nil {
		if cerr := q.getMatchTeamByRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMatchTeamByRolesStmt: %w", cerr)
		}
	}
	if q.getNotificationByOffsetStmt != nil {
		if cerr := q.getNotificationByOffsetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNotificationByOffsetStmt: %w", cerr)
		}
	}
	if q.getParticipationRequirementsStmt != nil {
		if cerr := q.getParticipationRequirementsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getParticipationRequirementsStmt: %w", cerr)
		}
	}
	if q.hasRoleAccessStmt != nil {
		if cerr := q.hasRoleAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hasRoleAccessStmt: %w", cerr)
		}
	}
	if q.hasUserAccessStmt != nil {
		if cerr := q.hasUserAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hasUserAccessStmt: %w", cerr)
		}
	}
	if q.increaseMatchTeamConfirmedParticipantsStmt != nil {
		if cerr := q.increaseMatchTeamConfirmedParticipantsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing increaseMatchTeamConfirmedParticipantsStmt: %w", cerr)
		}
	}
	if q.isGuildEnabledStmt != nil {
		if cerr := q.isGuildEnabledStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isGuildEnabledStmt: %w", cerr)
		}
	}
	if q.listDueNotificationsStmt != nil {
		if cerr := q.listDueNotificationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDueNotificationsStmt: %w", cerr)
		}
	}
	if q.listGuildMatchesStmt != nil {
		if cerr := q.listGuildMatchesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listGuildMatchesStmt: %w", cerr)
		}
	}
	if q.listGuildRoleAccessStmt != nil {
		if cerr := q.listGuildRoleAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listGuildRoleAccessStmt: %w", cerr)
		}
	}
	if q.listGuildUserAccessStmt != nil {
		if cerr := q.listGuildUserAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listGuildUserAccessStmt: %w", cerr)
		}
	}
	if q.listMatchModeratorsStmt != nil {
		if cerr := q.listMatchModeratorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMatchModeratorsStmt: %w", cerr)
		}
	}
	if q.listMatchStreamersStmt != nil {
		if cerr := q.listMatchStreamersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMatchStreamersStmt: %w", cerr)
		}
	}
	if q.listMatchTeamsStmt != nil {
		if cerr := q.listMatchTeamsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMatchTeamsStmt: %w", cerr)
		}
	}
	if q.listNotificationsStmt != nil {
		if cerr := q.listNotificationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNotificationsStmt: %w", cerr)
		}
	}
	if q.listNowAccessibleChannelsStmt != nil {
		if cerr := q.listNowAccessibleChannelsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNowAccessibleChannelsStmt: %w", cerr)
		}
	}
	if q.listNowDeletableChannelsStmt != nil {
		if cerr := q.listNowDeletableChannelsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNowDeletableChannelsStmt: %w", cerr)
		}
	}
	if q.listNowDueParticipationRequirementsStmt != nil {
		if cerr := q.listNowDueParticipationRequirementsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNowDueParticipationRequirementsStmt: %w", cerr)
		}
	}
	if q.nextMatchCounterStmt != nil {
		if cerr := q.nextMatchCounterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing nextMatchCounterStmt: %w", cerr)
		}
	}
	if q.removeGuildRoleAccessStmt != nil {
		if cerr := q.removeGuildRoleAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeGuildRoleAccessStmt: %w", cerr)
		}
	}
	if q.removeGuildUserAccessStmt != nil {
		if cerr := q.removeGuildUserAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeGuildUserAccessStmt: %w", cerr)
		}
	}
	if q.rescheduleMatchStmt != nil {
		if cerr := q.rescheduleMatchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing rescheduleMatchStmt: %w", cerr)
		}
	}
	if q.resetEventIDStmt != nil {
		if cerr := q.resetEventIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetEventIDStmt: %w", cerr)
		}
	}
	if q.updateCategoryIdStmt != nil {
		if cerr := q.updateCategoryIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCategoryIdStmt: %w", cerr)
		}
	}
	if q.updateGuildConfigStmt != nil {
		if cerr := q.updateGuildConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateGuildConfigStmt: %w", cerr)
		}
	}
	if q.updateMatchChannelAccessibilityStmt != nil {
		if cerr := q.updateMatchChannelAccessibilityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMatchChannelAccessibilityStmt: %w", cerr)
		}
	}
	if q.updateMatchEventIDStmt != nil {
		if cerr := q.updateMatchEventIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMatchEventIDStmt: %w", cerr)
		}
	}
	if q.updateParticipationRequirementsStmt != nil {
		if cerr := q.updateParticipationRequirementsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateParticipationRequirementsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                         DBTX
	tx                                         *sql.Tx
	addGuildConfigStmt                         *sql.Stmt
	addGuildRoleReadAccessStmt                 *sql.Stmt
	addGuildRoleWriteAccessStmt                *sql.Stmt
	addGuildUserAccessStmt                     *sql.Stmt
	addGuildUserWriteAccessStmt                *sql.Stmt
	addMatchStmt                               *sql.Stmt
	addMatchModeratorStmt                      *sql.Stmt
	addMatchStreamerStmt                       *sql.Stmt
	addMatchTeamStmt                           *sql.Stmt
	addMatchTeamResultsStmt                    *sql.Stmt
	addNotificationStmt                        *sql.Stmt
	addParticipationRequirementsStmt           *sql.Stmt
	closeParticipationEntryStmt                *sql.Stmt
	countAllMatchesStmt                        *sql.Stmt
	countAllNotificationsStmt                  *sql.Stmt
	countDisabledGuildsStmt                    *sql.Stmt
	countEnabledGuildsStmt                     *sql.Stmt
	countMatchesStmt                           *sql.Stmt
	countNotificationsStmt                     *sql.Stmt
	decreaseMatchTeamConfirmedParticipantsStmt *sql.Stmt
	deleteAllMatchModeratorsStmt               *sql.Stmt
	deleteAllMatchStreamersStmt                *sql.Stmt
	deleteAllMatchTeamsStmt                    *sql.Stmt
	deleteGuildConfigStmt                      *sql.Stmt
	deleteGuildMatchesStmt                     *sql.Stmt
	deleteMatchStmt                            *sql.Stmt
	deleteMatchListStmt                        *sql.Stmt
	deleteMatchModeratorStmt                   *sql.Stmt
	deleteMatchModeratorsStmt                  *sql.Stmt
	deleteMatchNotificationsStmt               *sql.Stmt
	deleteMatchStreamerStmt                    *sql.Stmt
	deleteMatchStreamersStmt                   *sql.Stmt
	deleteMatchTeamStmt                        *sql.Stmt
	deleteNotificationStmt                     *sql.Stmt
	deleteParticipationRequirementsStmt        *sql.Stmt
	disableGuildStmt                           *sql.Stmt
	getGuildConfigStmt                         *sql.Stmt
	getGuildConfigByCategoryStmt               *sql.Stmt
	getGuildRoleAccessStmt                     *sql.Stmt
	getGuildUserAccessStmt                     *sql.Stmt
	getMatchStmt                               *sql.Stmt
	getMatchTeamStmt                           *sql.Stmt
	getMatchTeamByRolesStmt                    *sql.Stmt
	getNotificationByOffsetStmt                *sql.Stmt
	getParticipationRequirementsStmt           *sql.Stmt
	hasRoleAccessStmt                          *sql.Stmt
	hasUserAccessStmt                          *sql.Stmt
	increaseMatchTeamConfirmedParticipantsStmt *sql.Stmt
	isGuildEnabledStmt                         *sql.Stmt
	listDueNotificationsStmt                   *sql.Stmt
	listGuildMatchesStmt                       *sql.Stmt
	listGuildRoleAccessStmt                    *sql.Stmt
	listGuildUserAccessStmt                    *sql.Stmt
	listMatchModeratorsStmt                    *sql.Stmt
	listMatchStreamersStmt                     *sql.Stmt
	listMatchTeamsStmt                         *sql.Stmt
	listNotificationsStmt                      *sql.Stmt
	listNowAccessibleChannelsStmt              *sql.Stmt
	listNowDeletableChannelsStmt               *sql.Stmt
	listNowDueParticipationRequirementsStmt    *sql.Stmt
	nextMatchCounterStmt                       *sql.Stmt
	removeGuildRoleAccessStmt                  *sql.Stmt
	removeGuildUserAccessStmt                  *sql.Stmt
	rescheduleMatchStmt                        *sql.Stmt
	resetEventIDStmt                           *sql.Stmt
	updateCategoryIdStmt                       *sql.Stmt
	updateGuildConfigStmt                      *sql.Stmt
	updateMatchChannelAccessibilityStmt        *sql.Stmt
	updateMatchEventIDStmt                     *sql.Stmt
	updateParticipationRequirementsStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                         tx,
		tx:                                         tx,
		addGuildConfigStmt:                         q.addGuildConfigStmt,
		addGuildRoleReadAccessStmt:                 q.addGuildRoleReadAccessStmt,
		addGuildRoleWriteAccessStmt:                q.addGuildRoleWriteAccessStmt,
		addGuildUserAccessStmt:                     q.addGuildUserAccessStmt,
		addGuildUserWriteAccessStmt:                q.addGuildUserWriteAccessStmt,
		addMatchStmt:                               q.addMatchStmt,
		addMatchModeratorStmt:                      q.addMatchModeratorStmt,
		addMatchStreamerStmt:                       q.addMatchStreamerStmt,
		addMatchTeamStmt:                           q.addMatchTeamStmt,
		addMatchTeamResultsStmt:                    q.addMatchTeamResultsStmt,
		addNotificationStmt:                        q.addNotificationStmt,
		addParticipationRequirementsStmt:           q.addParticipationRequirementsStmt,
		closeParticipationEntryStmt:                q.closeParticipationEntryStmt,
		countAllMatchesStmt:                        q.countAllMatchesStmt,
		countAllNotificationsStmt:                  q.countAllNotificationsStmt,
		countDisabledGuildsStmt:                    q.countDisabledGuildsStmt,
		countEnabledGuildsStmt:                     q.countEnabledGuildsStmt,
		countMatchesStmt:                           q.countMatchesStmt,
		countNotificationsStmt:                     q.countNotificationsStmt,
		decreaseMatchTeamConfirmedParticipantsStmt: q.decreaseMatchTeamConfirmedParticipantsStmt,
		deleteAllMatchModeratorsStmt:               q.deleteAllMatchModeratorsStmt,
		deleteAllMatchStreamersStmt:                q.deleteAllMatchStreamersStmt,
		deleteAllMatchTeamsStmt:                    q.deleteAllMatchTeamsStmt,
		deleteGuildConfigStmt:                      q.deleteGuildConfigStmt,
		deleteGuildMatchesStmt:                     q.deleteGuildMatchesStmt,
		deleteMatchStmt:                            q.deleteMatchStmt,
		deleteMatchListStmt:                        q.deleteMatchListStmt,
		deleteMatchModeratorStmt:                   q.deleteMatchModeratorStmt,
		deleteMatchModeratorsStmt:                  q.deleteMatchModeratorsStmt,
		deleteMatchNotificationsStmt:               q.deleteMatchNotificationsStmt,
		deleteMatchStreamerStmt:                    q.deleteMatchStreamerStmt,
		deleteMatchStreamersStmt:                   q.deleteMatchStreamersStmt,
		deleteMatchTeamStmt:                        q.deleteMatchTeamStmt,
		deleteNotificationStmt:                     q.deleteNotificationStmt,
		deleteParticipationRequirementsStmt:        q.deleteParticipationRequirementsStmt,
		disableGuildStmt:                           q.disableGuildStmt,
		getGuildConfigStmt:                         q.getGuildConfigStmt,
		getGuildConfigByCategoryStmt:               q.getGuildConfigByCategoryStmt,
		getGuildRoleAccessStmt:                     q.getGuildRoleAccessStmt,
		getGuildUserAccessStmt:                     q.getGuildUserAccessStmt,
		getMatchStmt:                               q.getMatchStmt,
		getMatchTeamStmt:                           q.getMatchTeamStmt,
		getMatchTeamByRolesStmt:                    q.getMatchTeamByRolesStmt,
		getNotificationByOffsetStmt:                q.getNotificationByOffsetStmt,
		getParticipationRequirementsStmt:           q.getParticipationRequirementsStmt,
		hasRoleAccessStmt:                          q.hasRoleAccessStmt,
		hasUserAccessStmt:                          q.hasUserAccessStmt,
		increaseMatchTeamConfirmedParticipantsStmt: q.increaseMatchTeamConfirmedParticipantsStmt,
		isGuildEnabledStmt:                         q.isGuildEnabledStmt,
		listDueNotificationsStmt:                   q.listDueNotificationsStmt,
		listGuildMatchesStmt:                       q.listGuildMatchesStmt,
		listGuildRoleAccessStmt:                    q.listGuildRoleAccessStmt,
		listGuildUserAccessStmt:                    q.listGuildUserAccessStmt,
		listMatchModeratorsStmt:                    q.listMatchModeratorsStmt,
		listMatchStreamersStmt:                     q.listMatchStreamersStmt,
		listMatchTeamsStmt:                         q.listMatchTeamsStmt,
		listNotificationsStmt:                      q.listNotificationsStmt,
		listNowAccessibleChannelsStmt:              q.listNowAccessibleChannelsStmt,
		listNowDeletableChannelsStmt:               q.listNowDeletableChannelsStmt,
		listNowDueParticipationRequirementsStmt:    q.listNowDueParticipationRequirementsStmt,
		nextMatchCounterStmt:                       q.nextMatchCounterStmt,
		removeGuildRoleAccessStmt:                  q.removeGuildRoleAccessStmt,
		removeGuildUserAccessStmt:                  q.removeGuildUserAccessStmt,
		rescheduleMatchStmt:                        q.rescheduleMatchStmt,
		resetEventIDStmt:                           q.resetEventIDStmt,
		updateCategoryIdStmt:                       q.updateCategoryIdStmt,
		updateGuildConfigStmt:                      q.updateGuildConfigStmt,
		updateMatchChannelAccessibilityStmt:        q.updateMatchChannelAccessibilityStmt,
		updateMatchEventIDStmt:                     q.updateMatchEventIDStmt,
		updateParticipationRequirementsStmt:        q.updateParticipationRequirementsStmt,
	}
}
