// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: matches.sql

package sqlc

import (
	"context"
)

const addMatch = `-- name: AddMatch :exec
INSERT INTO matches (
    guild_id,
    channel_id,
    channel_accessible_at,
    channel_delete_at,
    message_id,
    scheduled_at,
    required_participants_per_team,
    participation_confirmation_until,
    created_at,
    created_by,
    updated_at,
    updated_by
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12
)
`

type AddMatchParams struct {
	GuildID                        string `db:"guild_id"`
	ChannelID                      string `db:"channel_id"`
	ChannelAccessibleAt            int64  `db:"channel_accessible_at"`
	ChannelDeleteAt                int64  `db:"channel_delete_at"`
	MessageID                      string `db:"message_id"`
	ScheduledAt                    int64  `db:"scheduled_at"`
	RequiredParticipantsPerTeam    int64  `db:"required_participants_per_team"`
	ParticipationConfirmationUntil int64  `db:"participation_confirmation_until"`
	CreatedAt                      int64  `db:"created_at"`
	CreatedBy                      string `db:"created_by"`
	UpdatedAt                      int64  `db:"updated_at"`
	UpdatedBy                      string `db:"updated_by"`
}

func (q *Queries) AddMatch(ctx context.Context, arg AddMatchParams) error {
	_, err := q.exec(ctx, q.addMatchStmt, addMatch,
		arg.GuildID,
		arg.ChannelID,
		arg.ChannelAccessibleAt,
		arg.ChannelDeleteAt,
		arg.MessageID,
		arg.ScheduledAt,
		arg.RequiredParticipantsPerTeam,
		arg.ParticipationConfirmationUntil,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}

const deleteGuildMatches = `-- name: DeleteGuildMatches :exec
DELETE FROM matches WHERE guild_id = ?1
`

func (q *Queries) DeleteGuildMatches(ctx context.Context, guildID string) error {
	_, err := q.exec(ctx, q.deleteGuildMatchesStmt, deleteGuildMatches, guildID)
	return err
}

const deleteMatch = `-- name: DeleteMatch :exec
DELETE FROM matches WHERE channel_id = ?1
`

func (q *Queries) DeleteMatch(ctx context.Context, channelID string) error {
	_, err := q.exec(ctx, q.deleteMatchStmt, deleteMatch, channelID)
	return err
}

const getMatch = `-- name: GetMatch :one
SELECT
    channel_id,
    channel_accessible_at,
    channel_delete_at,
    message_id,
    scheduled_at,
    required_participants_per_team,
    participation_confirmation_until,
    created_at,
    created_by,
    updated_at,
    updated_by
FROM matches
WHERE channel_id = ?1
`

type GetMatchRow struct {
	ChannelID                      string `db:"channel_id"`
	ChannelAccessibleAt            int64  `db:"channel_accessible_at"`
	ChannelDeleteAt                int64  `db:"channel_delete_at"`
	MessageID                      string `db:"message_id"`
	ScheduledAt                    int64  `db:"scheduled_at"`
	RequiredParticipantsPerTeam    int64  `db:"required_participants_per_team"`
	ParticipationConfirmationUntil int64  `db:"participation_confirmation_until"`
	CreatedAt                      int64  `db:"created_at"`
	CreatedBy                      string `db:"created_by"`
	UpdatedAt                      int64  `db:"updated_at"`
	UpdatedBy                      string `db:"updated_by"`
}

func (q *Queries) GetMatch(ctx context.Context, channelID string) (GetMatchRow, error) {
	row := q.queryRow(ctx, q.getMatchStmt, getMatch, channelID)
	var i GetMatchRow
	err := row.Scan(
		&i.ChannelID,
		&i.ChannelAccessibleAt,
		&i.ChannelDeleteAt,
		&i.MessageID,
		&i.ScheduledAt,
		&i.RequiredParticipantsPerTeam,
		&i.ParticipationConfirmationUntil,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listGuildMatches = `-- name: ListGuildMatches :many
SELECT
    guild_id,
    channel_id,
    channel_accessible_at,
    channel_delete_at,
    message_id,
    scheduled_at,
    required_participants_per_team,
    participation_confirmation_until,
    created_at,
    created_by,
    updated_at,
    updated_by
FROM matches
WHERE guild_id = ?1
ORDER BY scheduled_at ASC
`

func (q *Queries) ListGuildMatches(ctx context.Context, guildID string) ([]Match, error) {
	rows, err := q.query(ctx, q.listGuildMatchesStmt, listGuildMatches, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.GuildID,
			&i.ChannelID,
			&i.ChannelAccessibleAt,
			&i.ChannelDeleteAt,
			&i.MessageID,
			&i.ScheduledAt,
			&i.RequiredParticipantsPerTeam,
			&i.ParticipationConfirmationUntil,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleMatch = `-- name: RescheduleMatch :exec
UPDATE matches
SET
    scheduled_at = ?1,
    required_participants_per_team = ?2,
    participation_confirmation_until = ?3,
    channel_accessible_at = ?4,
    channel_delete_at = ?5,
    updated_by = ?6
WHERE channel_id = ?7
`

type RescheduleMatchParams struct {
	ScheduledAt                    int64  `db:"scheduled_at"`
	RequiredParticipantsPerTeam    int64  `db:"required_participants_per_team"`
	ParticipationConfirmationUntil int64  `db:"participation_confirmation_until"`
	ChannelAccessibleAt            int64  `db:"channel_accessible_at"`
	ChannelDeleteAt                int64  `db:"channel_delete_at"`
	UpdatedBy                      string `db:"updated_by"`
	ChannelID                      string `db:"channel_id"`
}

func (q *Queries) RescheduleMatch(ctx context.Context, arg RescheduleMatchParams) error {
	_, err := q.exec(ctx, q.rescheduleMatchStmt, rescheduleMatch,
		arg.ScheduledAt,
		arg.RequiredParticipantsPerTeam,
		arg.ParticipationConfirmationUntil,
		arg.ChannelAccessibleAt,
		arg.ChannelDeleteAt,
		arg.UpdatedBy,
		arg.ChannelID,
	)
	return err
}
