// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type Access struct {
	Permission string `db:"permission"`
}

type GuildConfig struct {
	GuildID            string `db:"guild_id"`
	Enabled            int64  `db:"enabled"`
	CategoryID         string `db:"category_id"`
	ChannelDeleteDelay int64  `db:"channel_delete_delay"`
	MatchCounter       int64  `db:"match_counter"`
}

type Match struct {
	GuildID                        string `db:"guild_id"`
	ChannelID                      string `db:"channel_id"`
	ChannelAccessible              int64  `db:"channel_accessible"`
	ChannelAccessibleAt            int64  `db:"channel_accessible_at"`
	ChannelDeleteAt                int64  `db:"channel_delete_at"`
	MessageID                      string `db:"message_id"`
	ScheduledAt                    int64  `db:"scheduled_at"`
	ReminderCount                  int64  `db:"reminder_count"`
	RequiredParticipantsPerTeam    int64  `db:"required_participants_per_team"`
	ParticipationConfirmationUntil int64  `db:"participation_confirmation_until"`
	CreatedAt                      int64  `db:"created_at"`
	CreatedBy                      string `db:"created_by"`
	UpdatedAt                      int64  `db:"updated_at"`
	UpdatedBy                      string `db:"updated_by"`
}

type Moderator struct {
	ChannelID string `db:"channel_id"`
	UserID    string `db:"user_id"`
}

type RoleAccess struct {
	GuildID    string `db:"guild_id"`
	RoleID     string `db:"role_id"`
	Permission string `db:"permission"`
}

type Streamer struct {
	ChannelID string `db:"channel_id"`
	UserID    string `db:"user_id"`
	Url       string `db:"url"`
}

type Team struct {
	ChannelID             string `db:"channel_id"`
	RoleID                string `db:"role_id"`
	ConfirmedParticipants int64  `db:"confirmed_participants"`
	Score                 int64  `db:"score"`
	Time                  int64  `db:"time"`
	Screenshot            []byte `db:"screenshot"`
	Demo                  []byte `db:"demo"`
}

type UserAccess struct {
	GuildID    string `db:"guild_id"`
	UserID     string `db:"user_id"`
	Permission string `db:"permission"`
}
