services:
  league-discord-bot:
    container_name: league-discord-bot
    image: ghcr.io/jxsl13/league-discord-bot:latest
    restart: unless-stopped
    env_file:
      # contains the discord token
      # DISCORD_TOKEN="..."
      - secrets.env
    environment:
      TZ: "Europe/Berlin"
      BACKUP_INTERVAL: "168h"
      REMINDER_INTERVALS: "24h0m,1h0m,15m,5m,30s"
      GUILD_CHANNEL_DELETE_OFFSET: "24h"
      GUILD_CHANNEL_ACCESS_OFFSET: "168h"
      REQUIREMENTS_OFFSET: "24h"
      DSN: /data/league.db
    volumes:
      - ./volume/data:/data
