//go:build ignore

// Reference: https://hjr265.me/blog/go-tidbit-listing-all-time-zones-in-go/
package main

import (
	"archive/zip"
	"bytes"
	_ "embed"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
)

func checkerr(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func main() {
	fmt.Println(os.Environ())

	b, err := exec.Command("go", "env", "GOROOT").Output()
	checkerr(err)
	goroot := string(bytes.TrimSpace(b))

	zipname := filepath.Join(goroot, "lib", "time", "zoneinfo.zip")
	zipf, err := os.Open(zipname)
	checkerr(err)
	zipfi, err := zipf.Stat()
	checkerr(err)

	f, err := os.Create(os.Getenv("GOFILE"))
	checkerr(err)

	fmt.Fprintln(f, `// Code generated by "mktzlist.go"`)
	fmt.Fprintln(f, "//go:generate go run mktzlist.go")
	fmt.Fprintln(f)
	fmt.Fprintf(f, "package %s\n", os.Getenv("GOPACKAGE"))
	fmt.Fprintln(f)
	fmt.Fprintln(f, "import (")
	fmt.Fprintf(f, "\t_ %q\n", "time/tzdata")
	fmt.Fprintln(f, ")")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "var TimeZones = []string{")

	zr, err := zip.NewReader(zipf, zipfi.Size())
	checkerr(err)
	err = fs.WalkDir(zr, ".", func(path string, d fs.DirEntry, err error) error {
		if !d.IsDir() {
			fmt.Fprintf(f, "\t%q,\n", path)
		}
		return nil
	})
	checkerr(err)

	fmt.Fprintln(f, "}")
}
